name: release
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please input any text for confirmation'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Show versions
        run: |
          java -version
          clojure --version

      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: clj-cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clj-cache-

      - run: make release

