name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: clj-cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clj-cache-
      - run: make test-all
